### ISSUE TITLE
Clarification on Data Processing

### ISSUE THREAD

**Issue by ShijianXu** [lanxiang1017/DynamicBadPairMining_ICLR24#1]
Dear authors,

Thank you for sharing the code for your work. I am new to ECG processing, so please excuse any novice questions. In reviewing the PTB-benchmark paper, I noticed they utilized a sliding window approach to extract random ECG segments, such as 2.5s, as input. However, upon reviewing their code, I couldn't identify this specific processing step. Your code is based on their repo, yet I couldn't find this processing either. Could you please clarify how your data is shaped before inputting it into the model?

Thank you very much for your assistance!
Best regards.

**Comment by lanxiang1017** [comment]
Hi Shijian, 

We only use the original 100Hz ECG data, not their classification models with a sliding window strategy. Therefore, the input data shape is 12 * 1000, where 12 represents the number of leads and 1000 represents the length of the sequence. 

I hope this clarifies.

**Comment by ShijianXu** [comment]
Thanks for the clarification!
